name: webgame  # Явно указываем имя проекта

version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - webgame-network  # Изменено имя сети

  redis:
    image: redis:latest
    container_name: my-redis
    command: redis-server --requirepass mypassword
    environment:
      - REDIS_PASSWORD=mypassword
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - webgame-network  # Изменено имя сети
    restart: unless-stopped

networks:
  webgame-network:  # Изменено имя сети
    driver: bridge

volumes:
  postgres-data:
    name: webgame_postgres-data  # Явно указываем имя volume
  redis-data:
    name: webgame_redis-data    # Явно указываем имя volume